version: '3'

services:
  postgres:
    image: postgres:14.8
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    build: frontend/.
    restart: on-failure
    volumes:
      - bundles:/opt/app/bundles

  web:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    restart: unless-stopped
    volumes:
      - static:/opt/app/static
      - media:/opt/app/media
      - bundles:/opt/app/bundles
    ports:
      - "8000"
    env_file:
      - ./django/.env
    depends_on:
      - postgres
      - front
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000 --workers 3

  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - 80:80
      depends_on:
        - web
      volumes:
        - media:/opt/app/media
        - static:/opt/app/static

volumes:
  postgres_data:
  media:
  static:
  bundles:
