version: '3'

services:
  postgres:
    image: postgres:14.8
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    restart: on-failure
    working_dir: /opt/app/frontend

    build: ./frontend

  web:
    working_dir: /opt/app/django
    build: ./django

    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000

    env_file:
      - ./django/.env

    volumes:
      - media:/opt/app/media
      - static:/opt/app/static
    networks:
        - web_networks
    depends_on:
      - postgres
      - front

  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - 80:80
      depends_on:
        - web
      volumes:
        - media:/opt/app/media
        - static:/opt/app/static
      networks:
        - web_networks

networks:
  web_networks:

volumes:
  postgres_data:
  media:
  static:
