version: '3'

services:
  postgres:
    image: postgres:14.8
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    build: frontend/.
    restart: on-failure
    volumes:
      - static_volume:/opt/app/static/
    depends_on:
      - web
    expose:
      - 8000

  web:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    restart: unless-stopped
    volumes:
        - media_volume:/opt/app/media/
        - static_volume:/opt/app/static/
    expose:
      - 8000
    env_file:
      - ./django/.env
    depends_on:
      - postgres
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000 --workers 3

  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - 80:80
      depends_on:
        - web
      volumes:
        - media_volume:/opt/app/media/
        - static_volume:/opt/app/static/

volumes:
  postgres_data:
  media_volume:
  static_volume:
