# Generated by Django 3.2.15 on 2023-02-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230217_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
    ]
