# Generated by Django 3.2.15 on 2023-02-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230218_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Необработан'), (2, 'Передан в ресторан'), (3, 'Передан курьерам'), (4, 'Выполнен')], db_index=True, default=1, verbose_name='Статус заказа'),
        ),
    ]
