# Generated by Django 3.2.15 on 2023-02-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Выполнен'), (1, 'Необработан'), (2, 'Передан в ресторан'), (3, 'Передан курьерам')], db_index=True, default=1, verbose_name='Статус заказа'),
        ),
    ]
