# Generated by Django 3.2.15 on 2023-02-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230219_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
