# Generated by Django 3.2.15 on 2023-02-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('finish', 'Выполнен'), ('create', 'Необработан'), ('work', 'Передан в ресторан'), ('delivery', 'Передан курьерам')], db_index=True, default='create', max_length=8, verbose_name='Статус заказа'),
        ),
    ]
