# Generated by Django 3.2.15 on 2023-02-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True, verbose_name='Способ оплаты'),
        ),
    ]
