# Generated by Django 3.2.15 on 2023-02-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
