# Generated by Django 3.2.15 on 2023-03-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('not_set', '--------'), ('cash', 'Наличные'), ('card', 'Электронно')], db_index=True, default='not_set', max_length=7, verbose_name='Способ оплаты'),
        ),
    ]
