# Generated by Django 3.2.15 on 2023-03-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('4_finish', 'Выполнен'), ('1_create', 'Необработан'), ('2_work', 'Передан в ресторан'), ('3_delivery', 'Передан курьерам')], db_index=True, default='create', max_length=11, verbose_name='Статус заказа'),
        ),
    ]
