# Generated by Django 3.2.15 on 2023-03-20 13:15

from django.db import migrations

def fix_order_status_field(apps, schema_editor):

    old_status = ['create', 'work', 'delivery', 'finish']
    fixed_status = ['1_create', '2_work', '3_delivery', '4_finish']

    Order = apps.get_model("foodcartapp", "Order")
    for order in Order.objects.all():
        if order.status in old_status:
            order.status = fixed_status[old_status.index(order.status)]
            order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_status'),
    ]

    operations = [
        migrations.RunPython(fix_order_status_field)
    ]
